DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE user_role AS ENUM ('channel_partner', 'staff', 'manager', 'admin', 'rental_team');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'property_type') THEN
    CREATE TYPE property_type AS ENUM ('apartment', 'villa', 'plot', 'commercial', 'rental', 'other');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'lead_category') THEN
    CREATE TYPE lead_category AS ENUM ('normal', 'hot');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'lead_status') THEN
    CREATE TYPE lead_status AS ENUM ('new', 'in_progress', 'follow_up', 'converted', 'dropped', 'hot_lead', 'booked');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_channel') THEN
    CREATE TYPE notification_channel AS ENUM ('system', 'email');
  END IF;
END $$;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  phone VARCHAR(30) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role user_role NOT NULL,
  company_name VARCHAR(160),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(120) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  email VARCHAR(160),
  location VARCHAR(160) NOT NULL,
  investment_range VARCHAR(80) NOT NULL,
  property_type property_type NOT NULL DEFAULT 'apartment',
  lead_source VARCHAR(80) NOT NULL DEFAULT 'manual',
  lead_category lead_category NOT NULL DEFAULT 'normal',
  current_status lead_status NOT NULL DEFAULT 'new',
  notes TEXT,
  next_follow_up_at TIMESTAMPTZ,
  booked_at TIMESTAMPTZ,
  booking_value NUMERIC(12,2),
  created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  assigned_to BIGINT REFERENCES users(id) ON DELETE SET NULL,
  assigned_manager_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lead_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  status lead_status NOT NULL,
  changed_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lead_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  assigned_to BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  assigned_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  assigned_manager_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  note VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lead_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  actor_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action VARCHAR(80) NOT NULL,
  note TEXT,
  metadata_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notification_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES leads(id) ON DELETE SET NULL,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  type VARCHAR(60) NOT NULL,
  channel notification_channel NOT NULL DEFAULT 'system',
  subject VARCHAR(180) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_leads_updated_at ON leads;
CREATE TRIGGER trg_leads_updated_at
BEFORE UPDATE ON leads
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE VIEW vw_lead_source_report AS
SELECT lead_source, COUNT(*) AS total_leads
FROM leads
GROUP BY lead_source;

CREATE OR REPLACE VIEW vw_lead_status_report AS
SELECT current_status, COUNT(*) AS total_leads
FROM leads
GROUP BY current_status;

CREATE OR REPLACE VIEW vw_hot_lead_report AS
SELECT id, full_name, phone, location, assigned_manager_id, updated_at
FROM leads
WHERE lead_category = 'hot';

CREATE OR REPLACE VIEW vw_assignment_report AS
SELECT assigned_to, COUNT(*) AS total_assigned
FROM leads
WHERE assigned_to IS NOT NULL
GROUP BY assigned_to;

INSERT INTO users (full_name, email, phone, password_hash, role, company_name)
VALUES (
  'System Admin',
  'admin@one99properties.com',
  '9999999999',
  '$2a$10$2lQ0rYaI/uklHqNq6n61hO/7b1Q0GFlQ6z5N0fA0s2j9lFR7Naf6u',
  'admin',
  'One99 Properties'
)
ON CONFLICT (email) DO NOTHING;
